### ISSUE TITLE
How to reproduce the zero-shot result for SGD?

### ISSUE THREAD

**Issue by suntea233** [cuthalionn/Prompter#1]
I ran the code in `run_sgd.sh`, but I found that the domain in `train_data` and `test_data` is similar. Can this be called 'zero-shot'?

**Comment by cuthalionn** [comment]
Hi, thank you for your question!

The test split of the SGD [dataset ](https://github.com/google-research-datasets/dstc8-schema-guided-dialogue) includes domains both seen and unseen during training. In the paper, we report results only over the unseen domains. This experiment is set following the earlier baseline by [Wang et al.](https://aclanthology.org/2022.coling-1.42.pdf) hope this helps!

**Comment by suntea233** [comment]
Thank you for ur answering.
But i check the `prefix_data_loader.py`, and compare the domains between `data_train` and `data_test`, only `alarm, messaging, payment, trains` in `data_test` is unseen for `data_train`

**Comment by cuthalionn** [comment]
The SGD dataset has multiple different versions of each domain under the name: "services". Media_3, Buses_3, and Events_3 are all services which are unseen during training. I created a colab notebook to try to show this --> [here](https://drive.google.com/file/d/1SU49zdPK6rEsN566Jh1ZqWgjCY8coFqw/view?usp=sharing) (you will need to download and set the correct path for sgd data splits). 

According to the result from running this script following are all unseen during training: `{'Media_3', 'Messaging_1', 'RentalCars_3', 'Music_3', 'Payment_1', 'Buses_3', 'Flights_4', 'Trains_1', 'Events_3', 'Movies_3', 'Homes_2'}`

In the paper we only report results over these unseen services. This is also why Wang et al. reported results with Bus service (Buses_3 to be more specific).

I hope this clarifies, let me know if you have further concerns. Thank you!

**Comment by suntea233** [comment]
Thank you for your such detail answering.
